export const blogData = [
	{
		id: 1,
		title: "Eat Right : Some Basics About The Food We Eat",
		date: "Dec. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "food1.webp",
	},
	{
		id: 2,
		title: "Eat Right : Benefits of Eating The Right Food",
		date: "Feb. 14, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "2.jpg",
	},
	{
		id: 3,
		title: "Benefits Of Eating The Right Food : Physical Health",
		date: "Oct. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "3.jpg",
	},
	{
		id: 4,
		title: "Sports : Kheloge Nahi Toh Jeetoge Kaise",
		date: "Dec. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "4.jpg",
	},
	{
		id: 5,
		title: "What Is The Crypto Volatility Index (CVI)?",
		date: "jan. 8, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "5.jpg",
	},
	{
		id: 6,
		title: "What Is The Crypto Volatility Index (CVI)?",
		date: "Dec. 10, 2022",
		content: "The Crypto Volatility Index (CVI) is a decentralized solution used as a benchmark to track",
		category: "Sponsored",
		img: "6.jpg",
	},
];
